CREATE TABLE [dbo].[AMP_Generic_State](
	[StateId] [INT] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[StateAbbr] [VARCHAR](10) NOT NULL,
	[StateName] [NVARCHAR](200) NULL,
	[CountryId] [INT] NOT NULL,
	[IsHighRisk] [BIT] NULL,
	[StateCode] [NVARCHAR](10) NULL,
 CONSTRAINT [PK_AMP_Generic_State] PRIMARY KEY CLUSTERED 
(
	[StateId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[AMP_Generic_State]  WITH CHECK ADD  CONSTRAINT [FK_AMP_Generic_State_AMP_Generic_Country] FOREIGN KEY([CountryId])
REFERENCES [dbo].[AMP_Generic_Country] ([CountryId])
GO

ALTER TABLE [dbo].[AMP_Generic_State] CHECK CONSTRAINT [FK_AMP_Generic_State_AMP_Generic_Country]
GO
