CREATE TABLE [dbo].[AMP_Sec_ACL]
(
[ACLId] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[ACLTypeId] [smallint] NOT NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE TRIGGER [dbo].[Trg_SQLcm_AMP_Sec_ACL] ON [dbo].[AMP_Sec_ACL]
WITH EXECUTE AS CALLER
FOR INSERT, UPDATE, DELETE
AS EXTERNAL NAME [Trg_SQLcm_dbo_AMP_Sec_ACL].[CLRTriggers].[DMLTrigger]
GO
ALTER TABLE [dbo].[AMP_Sec_ACL] ADD CONSTRAINT [PK_AMP_Sec_ACL] PRIMARY KEY CLUSTERED ([ACLId]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_AMP_Sec_ACLType] ON [dbo].[AMP_Sec_ACL] ([ACLTypeId]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AMP_Sec_ACL] WITH NOCHECK ADD CONSTRAINT [FK_AMP_Sec_ACL_AMP_Sec_ACLType] FOREIGN KEY ([ACLTypeId]) REFERENCES [dbo].[AMP_Sec_ACLType] ([ACLTypeId]) ON DELETE CASCADE ON UPDATE CASCADE
GO
