CREATE TABLE [dbo].[AMP_Sec_ACLType]
(
[ACLTypeId] [smallint] NOT NULL,
[Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MustBound] [bit] NOT NULL CONSTRAINT [DF_AMP_Sec_ACLType_MustBound] DEFAULT ((0))
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE TRIGGER [dbo].[Trg_SQLcm_AMP_Sec_ACLType] ON [dbo].[AMP_Sec_ACLType]
WITH EXECUTE AS CALLER
FOR INSERT, UPDATE, DELETE
AS EXTERNAL NAME [Trg_SQLcm_dbo_AMP_Sec_ACLType].[CLRTriggers].[DMLTrigger]
GO
ALTER TABLE [dbo].[AMP_Sec_ACLType] ADD CONSTRAINT [PK_AMP_Sec_ACLType] PRIMARY KEY CLUSTERED ([ACLTypeId]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
